default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: administrator  # Il tuo nome utente Ubuntu
  password: 1q2w3e          # Se hai impostato una password, inseriscila qui; altrimenti lascialo vuoto
  host: localhost     # PostgreSQL locale

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: db_production
  username: administrator
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>  # Puoi configurare questa variabile d'ambiente per sicurezza
